spring.application.name=user-auth-system




jwt.secret=YOUR_SECRET_KEY

spring.datasource.url=YOUR_DB_URL
spring.datasource.username=mmmmmm
spring.datasource.password=mmmmmmm


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
